### ISSUE TITLE
Test Cases

### ISSUE THREAD

**Issue by castellanosr** [Edurate/edurate#1]
Need to make a test suite to make sure all of the functions are working as desired. To start off we need cases to check that the Google forms are downloaded correctly and then turned into a spread sheet to be used.

**Comment by bonnettd** [comment]
@toccinAC @millinj2 
Hey I was wondering if either of you two could explain to me some of the test cases that were written in test_edurate.py? My questions pertain to the last two functions that are being tested, the dictionary_create() function and the corp_eval() function. 
Could you explain why the test_dictionary_create_repeat() has an assertion of 
assert corp == [[(0, 1)], [(0, 3)], [(1, 1), (2, 1)]]
and why the second test_corp_eval_none() has an assertion of 
assert dict == {0: 2}
Thanks!

**Comment by toccinAC** [comment]
Hey sorry, I just saw this but those are how the gensim functions output.
