### ISSUE TITLE
Add and Delete Questions

### ISSUE THREAD

**Issue by castellanosr** [Edurate/edurate#11]
Kapfhammer ideally wants us to be able to add and delete questions from the form during the same semester. At minimum, however, the program should support evolution.

**Comment by castellanosr** [comment]
Kapfhammer ideally wants us to be able to add and delete questions from the form during the same semester. At minimum, however, the program should support evolution.

**Comment by colezAC** [comment]
@milleriAC Would you have a chance to work on this tomorrow night at some point? I have a start for it, but not too sure where to go from where I am.

**Comment by IzaakMiller** [comment]
Sure, can I see what your start is? I don't think the branch is updated.

**Comment by IzaakMiller** [comment]
I'm going to look at this website. https://developers.google.com/apps-script/reference/forms/?utm_campaign=app%20invites_series_autogenerate_forms_060616&utm_source=appdev&utm_medium=blog

**Comment by IzaakMiller** [comment]
I added a questions.py script and updated the parseargs and edurate program to accommodate the changes. It still needs to be tested.
