### ISSUE TITLE
 Archive Information

### ISSUE THREAD

**Issue by castellanosr** [Edurate/edurate#12]
The program must be able to remember responses so that we can see progress - dump information into the same spreadsheet, but use time stamps. Kapfhammer also asked "what if Google goes down?" We need to save everything to an rsv file.

**Comment by castellanosr** [comment]
The program must be able to remember responses so that we can see progress - dump information into the same spreadsheet, but use time stamps. Kapfhammer also asked "what if Google goes down?" We need to save everything to an rsv file.

**Comment by cookc3174** [comment]
Austin and I finished a basic function for adding to a csv.
