### ISSUE TITLE
Make Main Method

### ISSUE THREAD

**Issue by dillam** [Edurate/edurate#16]
Add your functions to the main method in the order that they need to be called.

**Comment by castellanosr** [comment]
Kapfhammer suggests one executable file. The questionnaire should be able to be sent out about every two weeks.

**Comment by burrowss** [comment]
Do we still need this issue? It seems like it is being covered by the edurate.py file

**Comment by wojnarn** [comment]
Well, we were going to finish the edurate.py file through this issue
