### ISSUE TITLE
Verifying Command Line Arguments 

### ISSUE THREAD

**Issue by castellanosr** [Edurate/edurate#4]
Need to have the program check that everything added in the command line is what the program will be looking for

**Comment by ZachAndrews98** [comment]
I can do this.

**Comment by burrowss** [comment]
Verify: Confidentiality, invalid command, spam filter, name of google sheet

**Comment by ZachAndrews98** [comment]
This has been merged into master, create a new issue if additional commands wish to be added or issues with commands arise.
