### ISSUE TITLE
Not always outputting the right LDA

### ISSUE THREAD

**Issue by burrowss** [Edurate/edurate#45]
The output seems to be randomly choosing which question to evaluate instead of just choosing from the responses of questions 7-10

**Comment by burrowss** [comment]
I'm thinking you might need to make the gensim evaluation function check to see if the first value/values of the questions are equal to 7, 8, 9 or 10, then it should evaluate instead of randomly choosing 4 questions to evaluate. Also is not ignoring the first row/column which is the question getting asked

**Comment by mariakimheinert** [comment]
Addressed in PR #54
