### ISSUE TITLE
Updating the README

### ISSUE THREAD

**Issue by sporrera** [Edurate/edurate#48]
Update README.md to include advice on all new features and how the system can be run and should function.

**Comment by mariakimheinert** [comment]
The initial setup command needs to include the package `ggplot`
EDIT: Nevermind. I missed the `pip install -r requirements.txt` command, which handles all of this.

**Comment by mariakimheinert** [comment]
But, it should be `pip3 install -r requirements.txt`

**Comment by sporrera** [comment]
Yes, I made note of this. Thank you!

**Comment by mariakimheinert** [comment]
@sporrera how is this issue going? We need some documentation on how to run the program with all its possible arguments.

**Comment by sporrera** [comment]
Yes, both @luoman and I are working to update the document. It is going well and will be completed and ready for complete integration by 1:30 this afternoon.

**Comment by Nikki-Luoma** [comment]
I believe that some sort of set up should be included in the README

## Initial Setup

Install gspread as well as oauth2client in your root directory in the repository
using the command: 

```shell
python3 -m pip install --user gspreed oauth2client 
```

From there create a Google sheet and a Google Form in Google Drive. In the
form create questions that allows your students to provide information
about how they feel about the teaching and the class. After you have recieved 
one submission from the Form, go to the response tap and click the green icon 
with the white cross through it. THis will allow you to link the Sheet to the
Form. You can create a new Sheet or link to a preexiting one.

**Comment by Nikki-Luoma** [comment]
## Usage

Edurate analysis professor/course questionnaires and uses natural language
processing detect the most common problems and output them into the terminal.
To run the program and output LDavis visualization, type `python3 edurate.py`
