### ISSUE TITLE
Add test cases for edurate_gensim.py

### ISSUE THREAD

**Issue by mariakimheinert** [Edurate/edurate#51]
There are no test cases for edurate_gensim.py. Each function should be tested with several test cases.

**Comment by cerdamejiaj** [comment]
There are test cases for the edurate_gensim.py in the test_suite branch.

**Comment by mariakimheinert** [comment]
@cerdamejiaj have these test cases been merged into master? If not, this issue should not be closed yet.

**Comment by cerdamejiaj** [comment]
@yeeunmariakim I closed it because this goes with the test suite which has an open issue and the test cases for gensim were already in the test suite. There is a merge request for the test suite. But if you want me to reopen it, I can.
