### ISSUE TITLE
Add test cases for read_responses.py

### ISSUE THREAD

**Issue by mariakimheinert** [Edurate/edurate#52]
There are no test cases for read_responses.py. The read_responses function needs to be tested with several test cases.

**Comment by lylet-AC** [comment]
Since this function takes in a csv file and reads it, should I create a fake csv file for this and have it return info from that file?

**Comment by mariakimheinert** [comment]
@lylet-AC generally, unit tests should not be testing any IO operations. One suggestion is to refactor the function so that the part of the function that reads in the CSV file as a list is moved to a different function than the part of the function that is parsing this list into the form that we want. You would only test the part of the function that is parsing the list into the form we want.

**Comment by bonnettd** [comment]
@lylet-AC How are these test cases coming along? I am just curious because I will merge all of the test cases into test_edurate.py as soon as all of the test cases are complete.
