### ISSUE TITLE
Add test cases for spreadsheet.py

### ISSUE THREAD

**Issue by mariakimheinert** [Edurate/edurate#53]
There are currently no test cases for spreadsheet.py. Specifically, all the functions except create_csv() have return values that can be tested.

**Comment by bonnettd** [comment]
@yeeunmariakim How are these test cases coming along? I am just curious because I would like to merge all of the test cases into the test_edurate.py file as soon as all test cases have been created

**Comment by mariakimheinert** [comment]
@bonnettd it would be better to keep test cases in their respective module files so that when someone is looking for a test case for a particular module, they do not have to navigate a very long file.

**Comment by mariakimheinert** [comment]
@bonnettd in fact, in the feature/i-1 branch, it would be good if you could separate the test cases by their modules into separate files. As soon as that's done, you can issue a pull request.

**Comment by bonnettd** [comment]
@yeeunmariakim okay I can do that. I will issue a pull request when it is ready

**Comment by mariakimheinert** [comment]
Addressed in PR #56
