### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by castellanosr** [Edurate/edurate#6]
Refactor the code as it comes in so that it is readable and formatted correctly

**Comment by ZachAndrews98** [comment]
I can refactor.

**Comment by ZachAndrews98** [comment]
Do people think we really need to have a refactoring issue? Each group is probably going to be creating their own files for their functions anyways, so it might be completely unnecessary and redundant to have people focusing on refactoring the code.

**Comment by burrowss** [comment]
I think its good to have so that just in case it gets messy we have some people that can help move stuff around. It's more of a last minute issue that should be done towards the end when we have the functions and files completed

**Comment by ZachAndrews98** [comment]
Alright, I see what you're saying.
