### ISSUE TITLE
Trouble Running - 'pandas'

### ISSUE THREAD

**Issue by castellanosr** [Edurate/edurate#65]
When I try to run in the terminal I get:
```shell
castellanosr@aldenv171:~/280 Projects/edurate$ python3 edurate.py
Traceback (most recent call last):
  File "edurate.py", line 9, in <module>
    from graphing import graph
  File "/home/c/castellanosr/280 Projects/edurate/graphing.py", line 5, in <module>
    import pandas as pd
ImportError: No module named 'pandas'
castellanosr@aldenv171:~/280 Projects/edurate$ 
```

If I am simply running this wrong we need to better explain how to run in the READme so it's easy for users.

**Comment by bristola** [comment]
Try and `pip3 install -r requirements.txt` again.  It seems like the module pandas is not installed locally on your computer or does not have the right version.  This library is in the requirements.txt so it should be installed when you run that command.  If it still doesn't work let me know.

**Comment by lylet-AC** [comment]
run the pip install -r requirements.txt with the flag `--user`

**Comment by bristola** [comment]
This should be changed in the README.md so that no one else has this issue.  As Tyler said the new command should be `pip3 install -r requirements.txt --user`

**Comment by burrowss** [comment]
should be pip3 install --user -r requirements.txt

**Comment by IzaakMiller** [comment]
This issue occurs because you do not have admin privileges on the computer you are using to run the `pip3 install -r requirements.txt`. Adding the `--user` at the end allows you to locally install it in your user file. The only people who will experience this issue are the ones who are not using accounts that have admin privileges.
