### ISSUE TITLE
add feature for selection of specific columns and rows for gensim analysis

### ISSUE THREAD

**Issue by toccinAC** [Edurate/edurate#68]
I believe we should add a feature so that the user can select a specific row or column so that the lda would be run on just one question or just one person's response. I would have to change the read_responses.py so that it records the columns as well. I would do it in the way that it reads from the csv like it does in Accelegator. I might also have to change the edurate_gensim.py so that the lda is proper. I also believe that the program should take in which question begins the textual responses that should be analyzed so that the column is not hard coded.

**Comment by bristola** [comment]
This is a good idea that should be implemented like in Accelegator.  Its not that necessary right now but it will be a nice feature to implement quickly.
