### ISSUE TITLE
Explanation of how to read NLP visual graph

### ISSUE THREAD

**Issue by castellanosr** [Edurate/edurate#72]
The NLP graph can be confusing to look at upon first glance. Documentation should be added to the READme on how to interpret it so that users get the maximum information from the analysis.

**Comment by sporrera** [comment]
I agree with @castellanosr , after running the commands to open the graphs, it is very difficult to understand what they are trying to show. Would the creator of the graphs be able to help with this?

**Comment by toccinAC** [comment]
I will do it.

**Comment by toccinAC** [comment]
Actually this has already been done, the information exists in the EdurateLDavis_Analysis.md. This file is pointed to in the README.md.
