### ISSUE TITLE
Compare past questionnaires

### ISSUE THREAD

**Issue by castellanosr** [Edurate/edurate#73]
Maria mentioned that the graphs currently only represent the most recent questionnaire. The client specified that he wants to be able to compare past questionnaires in order to see progress.

**Comment by castellanosr** [comment]
@dillam you worked with the google forms before, do you have any idea how to fix this issue?

**Comment by dillam** [comment]
You could separate responses collected on different days into different csv's. I don't know how the program shows only the most recent data. I think this is also a question for whoever worked on that.
