### ISSUE TITLE
Explain Your Functions

### ISSUE THREAD

**Issue by castellanosr** [Edurate/edurate#9]
We need descriptions of every function so that the code is easy to follow and so that the test suite team knows what each tested function should do. Explanations can be made as comments next to your function, in the ReadMe, or in the Wiki. List the inputs, outputs, and behaviour of your function. Make your functions return something even if they are just printing to help out our testers.

**Comment by burrowss** [comment]
Based on what we just discussed in class, we need to be adding comments into all of our source code. They should be about why the code works, not how
